apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secret
  namespace: dojangkok
spec:
  data:
    - secretKey: application.yaml
      remoteRef:
        key: dojangkok/prod/backend
