apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-route
  namespace: dojangkok
spec:
  parentRefs:
    - name: dojangkok-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: backend
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /oauth2
      backendRefs:
        - name: backend
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /login
      backendRefs:
        - name: backend
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /actuator
      backendRefs:
        - name: backend
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: chatting-be-route
  namespace: dojangkok
spec:
  parentRefs:
    - name: dojangkok-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/chat/v3
        - path:
            type: PathPrefix
            value: /api/v3/direct-chat
        - path:
            type: PathPrefix
            value: /ws/chat
      backendRefs:
        - name: chatting-be
          port: 8081
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-route
  namespace: dojangkok
spec:
  parentRefs:
    - name: dojangkok-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: frontend
          port: 3000
