# AI Server CI/CD Pipeline
# 위치: .github/workflows/ai-cicd.yml
#
# 트리거:
#   - PR → dev/main: lint-test, build-and-artifact
#   - Push main (PR 머지): lint-test, build-and-artifact, deploy
#   - workflow_dispatch: 모든 job 실행
#
# 패키지 관리: uv (pyproject.toml + uv.lock)
# 인증: GCP Workload Identity Federation (OIDC)
# 배포: In-place 배포 (VM 직접 업데이트)

name: AI Server CI/CD

# 동시 실행 방지
concurrency:
  group: ai-server-cicd-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [dev, main]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"

jobs:
  # ============================================
  # CI: Lint & Test
  # ============================================
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run Ruff Linter
        run: ruff check . || echo "::warning::Lint errors found (non-blocking)"

      - name: Run Ruff Formatter Check
        run: ruff format --check . || echo "::warning::Format issues found (non-blocking)"

      - name: Run Tests
        run: |
          if [ -d "tests" ]; then
            uv run pytest tests/ -v --cov=. --cov-report=xml
          else
            echo "No tests directory found, skipping tests"
          fi

  # ============================================
  # CI: Build & Artifact
  # ============================================
  build-and-artifact:
    name: Build & Artifact
    runs-on: ubuntu-22.04
    needs: lint-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: uv sync --frozen --no-dev

      - name: Verify Build
        run: |
          uv run python -m py_compile $(find . -name "*.py" -not -path "./.venv/*" -not -path "./venv/*" 2>/dev/null || echo "")
          echo "Build verification completed"

      - name: Create Artifact
        run: |
          mkdir -p dist
          tar -czvf dist/ai-server-${{ github.sha }}.tar.gz \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='__pycache__' \
            --exclude='.pytest_cache' \
            --exclude='.ruff_cache' \
            --exclude='*.pyc' \
            --exclude='venv' \
            --exclude='.venv' \
            .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-server-${{ github.sha }}
          path: dist/
          retention-days: 7

  # ============================================
  # CD: Deploy (main 브랜치만)
  # ============================================
  deploy:
    name: Deploy to GCP
    if: github.ref == 'refs/heads/main'
    needs: build-and-artifact
    runs-on: ubuntu-22.04
    environment: 1-bigbang
    permissions:
      contents: read
      id-token: write
      actions: read
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_ZONE: ${{ secrets.GCP_ZONE }}
      GCP_INSTANCE: ${{ secrets.GCP_INSTANCE }}
    steps:
      - name: Get Runner IP
        id: ip
        run: echo "ip=$(curl -s ifconfig.me)" >> $GITHUB_OUTPUT

      - name: Authenticate to GCP (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Add Firewall Rule
        run: |
          gcloud compute firewall-rules create github-actions-temp-${{ github.run_id }} \
            --allow=tcp:22 \
            --source-ranges=${{ steps.ip.outputs.ip }}/32 \
            --target-tags=ai-server \
            --project=${{ env.GCP_PROJECT_ID }} \
            --description="Temporary rule for GitHub Actions CD"
          echo "Firewall rule created for IP: ${{ steps.ip.outputs.ip }}"

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ai-server-${{ github.sha }}
          path: ./artifact

      - name: Deploy to VM
        run: |
          ARTIFACT_FILE=$(find ./artifact -name "*.tar.gz" | head -1)
          if [ -z "$ARTIFACT_FILE" ]; then
            echo "Artifact not found"
            exit 1
          fi
          echo "Deploying: $ARTIFACT_FILE"

          # Artifact 전송
          gcloud compute scp "$ARTIFACT_FILE" \
            ${{ env.GCP_INSTANCE }}:/tmp/ai-server-deploy.tar.gz \
            --zone=${{ env.GCP_ZONE }}

          # VM에서 배포 실행
          gcloud compute ssh ${{ env.GCP_INSTANCE }} \
            --zone=${{ env.GCP_ZONE }} \
            --command='
              set -e

              # uv 설치 (없는 경우)
              if ! command -v uv &> /dev/null; then
                echo "Installing uv..."
                curl -LsSf https://astral.sh/uv/install.sh | sh
              fi
              export PATH="$HOME/.local/bin:$PATH"

              # 서비스 중단
              sudo systemctl stop ai-server || true

              # 배포
              sudo mkdir -p /app/ai-server
              sudo tar -xzf /tmp/ai-server-deploy.tar.gz -C /app/ai-server

              # 권한 설정 (uv sync 전에 먼저 설정)
              sudo chown -R $(whoami):$(whoami) /app/ai-server

              # uv sync (uv.lock 변경 시에만 재설치)
              cd /app/ai-server
              NEW_HASH=$(md5sum uv.lock | cut -d" " -f1)
              OLD_HASH=""
              if [ -f ".venv/.uv_lock_hash" ]; then
                OLD_HASH=$(cat .venv/.uv_lock_hash)
              fi

              if [ "$NEW_HASH" != "$OLD_HASH" ] || [ ! -d ".venv" ]; then
                echo "uv.lock changed or .venv missing, installing..."
                rm -rf .venv
                $HOME/.local/bin/uv sync --frozen
                echo "$NEW_HASH" > .venv/.uv_lock_hash
                echo "Dependencies installed"
              else
                echo "uv.lock unchanged, skipping dependency install"
              fi

              # 서비스 시작
              sudo systemctl start ai-server

              # 정리
              rm -f /tmp/ai-server-deploy.tar.gz
            '

      - name: Health Check
        id: healthcheck
        run: |
          EXTERNAL_IP=$(gcloud compute instances describe ${{ env.GCP_INSTANCE }} \
            --zone=${{ env.GCP_ZONE }} \
            --format='get(networkInterfaces[0].accessConfigs[0].natIP)')

          echo "Health check: http://$EXTERNAL_IP:8000/health"

          for i in {1..12}; do
            if curl -s -f "http://$EXTERNAL_IP:8000/health" > /dev/null; then
              echo "Health check passed"
              echo "status=success" >> $GITHUB_OUTPUT
              exit 0
            fi
            echo "Attempt $i/12 - Waiting..."
            sleep 5
          done

          echo "Health check failed"
          echo "status=failed" >> $GITHUB_OUTPUT
          exit 1

      - name: Remove Firewall Rule
        if: always()
        run: |
          gcloud compute firewall-rules delete github-actions-temp-${{ github.run_id }} \
            --project=${{ env.GCP_PROJECT_ID }} \
            --quiet || true
          echo "Firewall rule removed"
