# AI Server CD Pipeline
# 위치: .github/workflows/ai-cd.yml
#
# 트리거: main 브랜치 push (자동), 수동 (workflow_dispatch)
# 인증: GCP Workload Identity Federation (OIDC)
# 배포: In-place 배포 (VM 직접 업데이트)

name: AI Server CD

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_ZONE: ${{ secrets.GCP_ZONE }}
  GCP_INSTANCE: ${{ secrets.GCP_INSTANCE }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      id-token: write
      actions: read
    steps:
      - name: Authenticate to GCP (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Download Artifact
        id: artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ./artifact

          RUN_ID=$(gh run list \
            --repo ${{ github.repository }} \
            --workflow="AI Server CI" \
            --branch=main \
            --status=success \
            --limit=1 \
            --json databaseId \
            --jq '.[0].databaseId')

          if [ -z "$RUN_ID" ]; then
            echo "No successful CI run found"
            exit 1
          fi

          echo "Downloading artifact from run: $RUN_ID"
          gh run download "$RUN_ID" --repo ${{ github.repository }} --dir ./artifact

          ARTIFACT_FILE=$(find ./artifact -name "*.tar.gz" | head -1)
          if [ -z "$ARTIFACT_FILE" ]; then
            echo "Artifact not found"
            exit 1
          fi
          echo "file=$ARTIFACT_FILE" >> $GITHUB_OUTPUT

      - name: Deploy to VM
        run: |
          # Artifact 전송
          gcloud compute scp ${{ steps.artifact.outputs.file }} \
            ${{ env.GCP_INSTANCE }}:/tmp/ai-server-deploy.tar.gz \
            --zone=${{ env.GCP_ZONE }}

          # VM에서 배포 실행
          gcloud compute ssh ${{ env.GCP_INSTANCE }} \
            --zone=${{ env.GCP_ZONE }} \
            --command='
              set -e

              # 백업 생성 (최근 3개만 유지)
              BACKUP_DIR="/app/ai-server-backup-$(date +%Y%m%d%H%M%S)"
              if [ -d "/app/ai-server" ]; then
                sudo cp -r /app/ai-server "$BACKUP_DIR"
                echo "Backup created: $BACKUP_DIR"
                # 오래된 백업 정리
                ls -dt /app/ai-server-backup-* 2>/dev/null | tail -n +4 | xargs -r sudo rm -rf
              fi

              # 서비스 중단
              sudo systemctl stop ai-server || true

              # 배포
              sudo mkdir -p /app/ai-server
              sudo tar -xzf /tmp/ai-server-deploy.tar.gz -C /app/ai-server

              # venv 설정 (requirements.txt 변경 시에만 재설치)
              cd /app/ai-server
              NEW_HASH=$(md5sum requirements.txt | cut -d" " -f1)
              OLD_HASH=""
              if [ -f "venv/.requirements_hash" ]; then
                OLD_HASH=$(cat venv/.requirements_hash)
              fi

              if [ "$NEW_HASH" != "$OLD_HASH" ] || [ ! -d "venv" ]; then
                echo "Requirements changed or venv missing, installing..."
                sudo rm -rf venv
                sudo python3 -m venv venv
                sudo /app/ai-server/venv/bin/pip install --upgrade pip -q
                sudo /app/ai-server/venv/bin/pip install -r requirements.txt -q
                echo "$NEW_HASH" | sudo tee venv/.requirements_hash > /dev/null
                echo "Dependencies installed"
              else
                echo "Requirements unchanged, skipping venv setup"
              fi

              # 권한 설정
              sudo chown -R jsh:jsh /app/ai-server

              # 서비스 시작
              sudo systemctl start ai-server

              # 정리
              rm -f /tmp/ai-server-deploy.tar.gz
            '

      - name: Health Check
        id: healthcheck
        run: |
          EXTERNAL_IP=$(gcloud compute instances describe ${{ env.GCP_INSTANCE }} \
            --zone=${{ env.GCP_ZONE }} \
            --format='get(networkInterfaces[0].accessConfigs[0].natIP)')

          echo "Health check: http://$EXTERNAL_IP:8000/health"

          for i in {1..12}; do
            if curl -s -f "http://$EXTERNAL_IP:8000/health" > /dev/null; then
              echo "Health check passed"
              echo "status=success" >> $GITHUB_OUTPUT
              exit 0
            fi
            echo "Attempt $i/12 - Waiting..."
            sleep 5
          done

          echo "Health check failed"
          echo "status=failed" >> $GITHUB_OUTPUT
          exit 1

      - name: Rollback on Failure
        if: failure() && steps.healthcheck.outputs.status == 'failed'
        run: |
          gcloud compute ssh ${{ env.GCP_INSTANCE }} \
            --zone=${{ env.GCP_ZONE }} \
            --command='
              set -e
              LATEST_BACKUP=$(ls -td /app/ai-server-backup-* 2>/dev/null | head -1)

              if [ -n "$LATEST_BACKUP" ]; then
                echo "Rolling back to: $LATEST_BACKUP"
                sudo systemctl stop ai-server || true
                sudo rm -rf /app/ai-server
                sudo mv "$LATEST_BACKUP" /app/ai-server
                sudo systemctl start ai-server
                echo "Rollback completed"
              else
                echo "No backup found"
                exit 1
              fi
            '
