# AI Server CI Pipeline
# 위치: .github/workflows/ai-ci.yml
#
# 트리거 매트릭스:
#   - PR feat/* → dev: lint-test
#   - Push dev: lint-test, build
#   - PR dev/hotfix/* → main: lint-test, build
#   - Push main: artifact
#
# 패키지 관리: uv (pyproject.toml + uv.lock)

name: AI Server CI

on:
  workflow_dispatch:  # 수동 실행
  push:
    branches: [main, dev]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'
      - 'docs/**'

env:
  PYTHON_VERSION: "3.10"

jobs:
  # ============================================
  # Lint & Test
  # ============================================
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-22.04
    continue-on-error: true  # lint 실패해도 CI 통과
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run Ruff Linter
        run: ruff check . || echo "::warning::Lint errors found (non-blocking)"

      - name: Run Ruff Formatter Check
        run: ruff format --check . || echo "::warning::Format issues found (non-blocking)"

      - name: Run Tests
        run: |
          if [ -d "tests" ]; then
            uv run pytest tests/ -v --cov=. --cov-report=xml
          else
            echo "No tests directory found, skipping tests"
          fi

  # ============================================
  # Build
  # dev push, main PR에서만 실행 (main push 제외)
  # ============================================
  build:
    name: Build
    runs-on: ubuntu-22.04
    needs: lint-test
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/dev') ||
      (github.event_name == 'pull_request' && github.base_ref == 'main')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: uv sync --frozen --no-dev

      - name: Verify Build
        run: |
          # Python 문법 검증
          uv run python -m py_compile $(find . -name "*.py" -not -path "./.venv/*" -not -path "./venv/*" 2>/dev/null || echo "")
          echo "Build verification completed"

  # ============================================
  # Upload Artifact
  # main push에서만 실행
  # ============================================
  artifact:
    name: Upload Artifact
    runs-on: ubuntu-22.04
    needs: lint-test
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Artifact
        run: |
          mkdir -p dist
          # 소스코드 패키징 (의존성 제외)
          tar -czvf dist/ai-server-${{ github.sha }}.tar.gz \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='__pycache__' \
            --exclude='.pytest_cache' \
            --exclude='.ruff_cache' \
            --exclude='*.pyc' \
            --exclude='venv' \
            --exclude='.venv' \
            .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-server-${{ github.sha }}
          path: dist/
          retention-days: 7
