apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chatting-be-secret
  namespace: dojangkok
  labels:
    app.kubernetes.io/name: chatting-be
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: chatting-be-secret
  data:
    - secretKey: application.yaml
      remoteRef:
        key: dojangkok/dev/chatting-be
