apiVersion: v1
kind: Service
metadata:
  name: chatting-be
  namespace: dojangkok
  labels:
    app.kubernetes.io/name: chatting-be
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chatting-be
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
