apiVersion: v1
kind: ServiceAccount
metadata:
  name: fe-sa
  namespace: dojangkok
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: be-sa
  namespace: dojangkok
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-sa
  namespace: dojangkok
automountServiceAccountToken: false
