# 정의할 워크 플로우의 이름
name: Dojangkok Server CI/CD

# 워크플로우를 실행할 이벤트 결정 및 매핑
on:
  push:
    branches: [dev, main]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [dev, main]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

# 실행할 작업을 정의
jobs:
  test-and-build: # 테스트를 수행하는 단계
    runs-on: ubuntu-latest
    steps:
      # 1. 소스코드 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v6
      # 2. Java 21 런타임 설정
      - name: Set up Java Runtime
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'gradle'
      # 3. gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # 4. 테스트 수행
      - name: Run tests
        run: ./gradlew test --no-daemon -x test
      # 5. JAR 파일 빌드 (테스트를 선행하였으므로 바로 빌드 수행)
      - name: Build JAR
        run: ./gradlew bootJar --no-daemon -x test
      # 6. 빌드된 JAR 파일을 아티팩트로 업로드
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v6
        with:
          name: dojangkok-server-jar
          path: build/libs/*.jar
          retention-days: 7
  deploy: # 빌드 파일을 가지고 배포를 수행하는 단계
    if: github.ref == 'refs/heads/main'
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      # 0. Github Action Runner IP 획득
      - name: Get GitHub Actions Runner IP
        id: ip
        run: echo "ipv4=$(curl -s https://checkip.amazonaws.com)" >> $GITHUB_OUTPUT
      # 1. AWS 자격증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      # 2. Github Action Runner IP 를 보안그룹에 임시허용
      - name: Add GitHub IP to Security Group
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_SG_ID }} \
            --protocol tcp --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32 \
            --tag-specifications 'ResourceType=security-group-rule,Tags=[{Key=Name,Value=GithubActions}]' || true
      # 3. 빌드한 JAR 아티펙트 다운로드
      - name: Download JAR Artifact
        uses: actions/download-artifact@v6
        with:
          name: dojangkok-server-jar
          path: build/libs
      # 4. 대상 서버 SSH 접속을 위한 .pem Key 생성
      - name: Create PEM key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./key.pem
          chmod 600 ./key.pem
      # 5. 대상 서버로 아티펙트 파일 전송 및 실행
      - name: Deploy to Target Server
        env:
          TARGET_IP: ${{ secrets.TARGET_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}
          REMOTE_DIR: "/home/${{ secrets.SSH_USER }}/server"
          JAR_NAME: "dojangkok-server.jar"
        run: |
          echo "JAR 파일 전송..."
          scp -i ./key.pem -o StrictHostKeyChecking=no build/libs/*.jar $SSH_USER@$TARGET_IP:$REMOTE_DIR/$JAR_NAME
          echo "배포 시작..."
          ssh -i ./key.pem -o StrictHostKeyChecking=no $SSH_USER@$TARGET_IP << EOF
            set -e
            cd $REMOTE_DIR
            aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/backend/application.yaml ./application.yaml
            echo "Systemd 서비스 재시작..."
            sudo systemctl restart dojangkok-server
          EOF
          rm -f ./key.pem
      # 6. 배포 후 Health Check
      - name: Health Check
        env:
          SERVICE_URL: ${{ secrets.SERVICE_URL }}
        run: |
          echo "Health Check 시작..."
          MAX_RETRIES=10
          RETRY_INTERVAL=15
          for i in $(seq 1 $MAX_RETRIES); do
            HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$SERVICE_URL/actuator/health" || echo "000")
            if [ "$HTTP_STATUS" = "200" ]; then
              echo "Health Check 성공 (HTTP $HTTP_STATUS)"
              exit 0
            fi
            echo "시도 $i/$MAX_RETRIES: HTTP $HTTP_STATUS - ${RETRY_INTERVAL}초 후 재시도..."
            sleep $RETRY_INTERVAL
          done
          echo "Health Check 실패: 서비스가 응답하지 않습니다."
          exit 1
      # 7. Github Action Runner IP 임시허용 해제
      - name: Revoke GitHub IP from Security Group
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_SG_ID }} \
            --protocol tcp --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32 || true