apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: patches/backend-hpa.yaml

# base가 이미 dev 기본값이므로 최소한의 오버라이드만 정의.
# CI에서 image tag를 업데이트할 때 이 섹션을 수정한다.
# backend, ai-server는 HPA가 replicas를 관리하므로 여기서 제외
replicas:
- count: 1
  name: frontend
- count: 1
  name: chatting-be

images:
- name: 662505429975.dkr.ecr.ap-northeast-2.amazonaws.com/dev-dojangkok-ai
  newTag: 426b41fc459eadd516bf880071be1b317fac276b
- name: 662505429975.dkr.ecr.ap-northeast-2.amazonaws.com/dev-dojangkok-be
  newTag: fe8177ae0a146be5de0ebe4f4a9bbdf73d2911aa
- name: 662505429975.dkr.ecr.ap-northeast-2.amazonaws.com/dev-dojangkok-chatting-be
  newTag: 646a173b5b5f0008ac7686446cb7d1bd500c96e9
- name: 662505429975.dkr.ecr.ap-northeast-2.amazonaws.com/dev-dojangkok-fe
  newTag: b83a09d166a63330c725e0c80bcb7eb4be30fbc9
