apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: patches/backend-hpa.yaml

# base가 이미 dev 기본값이므로 최소한의 오버라이드만 정의.
# CI에서 image tag를 업데이트할 때 이 섹션을 수정한다.
# backend, ai-server는 HPA가 replicas를 관리하므로 여기서 제외
replicas:
- count: 1
  name: frontend
- count: 1
  name: chatting-be

images:
- name: 662505429975.dkr.ecr.ap-northeast-2.amazonaws.com/dev-dojangkok-ai
  newTag: 426b41fc459eadd516bf880071be1b317fac276b
- name: 662505429975.dkr.ecr.ap-northeast-2.amazonaws.com/dev-dojangkok-be
  newTag: 3100f977d42c2fbdd9afafd8bd0d042951ef17f0
- name: 662505429975.dkr.ecr.ap-northeast-2.amazonaws.com/dev-dojangkok-chatting-be
  newTag: 4d27a12fc46b293304a53c70beb727abd6d4ffee
- name: 662505429975.dkr.ecr.ap-northeast-2.amazonaws.com/dev-dojangkok-fe
  newTag: 1e847c660cd76e1406a958dcf797d666ecdd595c
