apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-server-secret
  namespace: dojangkok
  labels:
    app.kubernetes.io/name: ai-server
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ai-server-secret
  dataFrom:
    - extract:
        key: dojangkok/dev/ai-server
