apiVersion: v1
kind: Service
metadata:
  name: ai-server
  namespace: dojangkok
  labels:
    app.kubernetes.io/name: ai-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ai-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
